const color = {
  primary: null,
  onPrimary: null,
  primaryContainer: null,
  onPrimaryContainer: null,
  inversePrimary: null,
  secondary: null,
  onSecondary: null,
  secondaryContainer: null,
  onSecondaryContainer: null,
  tertiary: null,
  onTertiary: null,
  tertiaryContainer: null,
  onTertiaryContainer: null,
  error: null,
  onError: null,
  errorContainer: null,
  onErrorContainer: null,
  surface: null,
  surfaceDim: null,
  surfaceBright: null,
  surfaceContainerLowest: null,
  surfaceContainerLow: null,
  surfaceContainer: null,
  surfaceContainerHigh: null,
  surfaceContainerHighest: null,
  onSurface: null,
  surfaceVariant: null,
  onSurfaceVariant: null,
  surfaceTint: null,
  inverseSurface: null,
  onInverseSurface: null,
  background: null,
  onBackground: null,
  outline: null,
  outlineVariant: null,
  shadow: null,
  scrim: null,
};

export default color;
