env:
  browser: true
  es2021: true
plugins:
  - solid
extends:
  - eslint:recommended
  - plugin:jsx-a11y/recommended
  - plugin:solid/typescript
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns: ['**/dist/**']
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_$'
      varsIgnorePattern: '^_$'
